#!/bin/sh

case "$2" in
    POST-INSTALL)
    # copy xdg
    if [ ! -d "/usr/local/etc/xdg/" ] ; then
      mkdir -p /usr/local/etc/xdg/
    fi
    cp -af /usr/local/share/furybsd/xfce-settings/etc/xdg/*   /usr/local/etc/xdg/
    ;;
esac

exit 0
