#!/bin/sh

# Only run as superuser
if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

cwd="`realpath | sed 's|/scripts||g'`"

sh ${cwd}/furybsd-make-ports

pkg upgrade -r furybsd -fy
