#!/bin/sh

# Only run as superuser
if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

if [ -f "/var/db/portsnap/INDEX" ] ; then
  portsnap fetch update
else
  portsnap fetch extract
fi

if [ -f "/usr/local/sbin/lightdm" ] ; then
  export DESKTOP="xfce"
fi
if [ -f "/usr/local/sbin/gdm" ] ; then
  export DESKTOP="gnome"
fi
if [ -f "/usr/local/bin/sddm" ] ; then
  export DESKTOP="kde"
fi

cache="/usr/local/furybsd/cache"
ports="/usr/ports"
repourl="/usr/local/etc/pkg/repos"
repofile="/usr/local/etc/pkg/repos/furybsd.conf"
repodir="/usr/local/furybsd/cache/furybsd-packages"

if [ ! -d "${cache}" ] ; then
  mkdir -p $[cache}
fi

if [ -d "${repodir}" ] ; then
  rm -rf ${repodir}
fi

mkdir ${repodir}

cd ${cache} && rm master.zip
rm -rf ${cache}/furybsd-ports-master
cd ${cache} && fetch https://github.com/furybsd/furybsd-ports/archive/master.zip
cd ${cache} && unzip master.zip
cd ${cache}/furybsd-ports-master && ./mkport.sh x11-themes/furybsd-wallpapers
cd ${ports}/x11-themes/furybsd-wallpapers && make package
cp ${ports}/x11-themes/furybsd-wallpapers/work/pkg/* ${repodir}
cd ${cache}/furybsd-ports-master && ./mkport.sh sysutils/furybsd-dsbdriverd
cd ${ports}/sysutils/furybsd-dsbdriverd && make package
cp ${ports}/sysutils/furybsd-dsbdriverd/work/pkg/* ${repodir}
cd ${cache}/furybsd-ports-master && ./mkport.sh x11-drivers/furybsd-xorg-tool
cd ${ports}/x11-drivers/furybsd-xorg-tool && make package
cp ${ports}/x11-drivers/furybsd-xorg-tool/work/pkg/* ${repodir}
cd ${cache}/furybsd-ports-master && ./mkport.sh sysutils/furybsd-update
cd ${ports}/sysutils/furybsd-update && make package
cp ${ports}/sysutls/furybsd-update/work/pkg/* ${repodir}
case $desktop in
  'kde')
    cd ${cache}/furybsd-ports-master && ./mkport.sh x11/furybsd-kde-desktop
    cd ${ports}/x11/furybsd-kde-desktop && make package
    cp ${ports}/x11/furybsd-kde-desktop/work/pkg/* ${repodir}

    ;;
  'gnome')
    cd ${cache}/furybsd-ports-master && ./mkport.sh x11/furybsd-gnome-desktop
    cd ${ports}/x11/furybsd-gnome-desktop && make package
    cp ${ports}/x11/furybsd-gnome-desktop/work/pkg/* ${repodir}
    ;;
  *)
    cd ${cache}/furybsd-ports-master && ./mkport.sh x11/furybsd-xfce-settings
    cd ${ports}/x11/furybsd-xfce-settings && make package
    cp ${ports}/x11/furybsd-xfce-settings/work/pkg/* ${repodir}
    cd ${cache}/furybsd-ports-master && ./mkport.sh x11/furybsd-xfce-desktop
    cd ${ports}/x11/furybsd-xfce-desktop && make package
    cp ${ports}/x11/furybsd-xfce-desktop/work/pkg/* ${repodir}
    ;;
esac

if [ ! -d "${repourl}" ] ; then
  mkdir -p ${repourl}
fi

cat <<EOF | tee ${repofile}
furybsd: {
    url: "file:///usr/local/furybsd/cache/furybsd-packages",
    mirror_type: "srv",
    enabled: yes,
    priority: 100
}
EOF

pkg repo ${repodir}
